server:
  port: 8500
#eureka相关配置
eureka:
  client:
    security:
      user:
        name: c649d6185032697ada52a13e7ea75bf3
        password: f3567443d4fd7988fbed18d736c64091
    service-url:
      defaultZone: http://${eureka.client.security.user.name}:${eureka.client.security.user.password}@localhost:8761/eureka/
    # 针对新服务上线, Eureka client获取不及时的问题，在测试环境，可以适当提高Client端拉取Server注册信息的频率，默认：30秒
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      mysql:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/vblog?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=GMT%2B8
        username: root
        password:
        # 初始化大小，最小，最大
        initialSize: 20
        minIdle: 5
        maxActive: 200
        #连接等待超时时间
        maxWait: 60000
        #配置隔多久进行一次检测(检测可以关闭的空闲连接)
        timeBetweenEvictionRunsMillis: 60000
        #配置连接在池中的最小生存时间
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        dbcp:
          remove-abandoned: true
          #泄露的连接可以被删除的超时时间（秒），该值应设置为应用程序查询可能执行的最长时间
          remove-abandoned-timeout: 180
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500