eureka:
  instance:
    prefer-ip-address: true
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    secure-port-enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${spring.cloud.client.ip-address}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
    response-cache-auto-expiration-in-seconds: 60
    renewal-percent-threshold: 0.85
    leaseRenewalIntervalInseconds: 10